zgflw: Joystick and Gamepad support
michal-z/zig-gamedev pull request #148
Opened 2022-11-01 04:00 UTC by Pyrolistical

Please be critical on how I exposed the glfw API.

2022-11-01 18:45 UTC, michal-z commented
Thanks for the PR!

I will review it tomorrow morning.

2022-11-02 11:13 UTC, michal-z commented
I would like to expose `Joystick` as an opaque pointer. `jid` can be just a `u4` we don't need an enum.

```zig
pub const Joystick = *opaque {
    pub fn getGuid(joystick: Joystick) [:0]const u8 {
        return std.mem.span(glfwGetJoystickGUID(@intCast(i32, @ptrToInt(joystick))).?);
    }
    extern fn glfwGetJoystickGUID(jid: i32) ?[*:0]const u8;

    pub fn getName(joystick: Joystick) [:0]const u8 {
        return std.mem.span(glfwGetJoystickName(@intCast(i32, @ptrToInt(joystick))).?);
    }
    extern fn glfwGetJoystickName(jid: i32) ?[*:0]const u8;
};

pub fn getJoystick(jid: u4) ?Joystick {
    if (isJoystickPresent(jid)) {
        return @intToPtr(Joystick, @intCast(usize, jid));
    }
    return null;
}

pub fn isJoystickPresent(jid: u4) bool {
    return glfwJoystickPresent(@intCast(i32, jid)) != 0;
}
extern fn glfwJoystickPresent(jid: i32) i32;
```

2022-11-02 11:18 UTC, michal-z commented
Or perhaps, it would be better to define it like:

```zig
pub const Joystick = struct {
    id: u4,

    pub fn getGuid(joystick: Joystick) [:0]const u8 {
        return std.mem.span(glfwGetJoystickGUID(@intCast(i32, @ptrToInt(joystick))).?);
    }
    extern fn glfwGetJoystickGUID(jid: i32) ?[*:0]const u8;

    pub fn getName(joystick: Joystick) [:0]const u8 {
        return std.mem.span(glfwGetJoystickName(@intCast(i32, @ptrToInt(joystick))).?);
    }
    extern fn glfwGetJoystickName(jid: i32) ?[*:0]const u8;
};
```

What do you think?

2022-11-02 18:52 UTC, Pyrolistical commented
I like the struct version. I've made the API easier to use by having init return an optional joystick and giving the ability to "upgrade" a joystick to a gamepad.

I've made those changes, take another look.

2022-11-02 22:57 UTC, michal-z requested changes
Thanks. I've added few comments.

2022-11-02 22:57 UTC, michal-z commented on libs/zglfw/src/zglfw.zig
> +    pub fn present(self: Joystick) bool {
Let's call it `isPresent()`.

2022-11-02 22:57 UTC, michal-z commented on libs/zglfw/src/zglfw.zig
> +    pub fn getGUID(self: Joystick) [*:0]const u8 {
Let's call it `getGuid()` (Zig convention). Return type should be `[:0]` (requires `std.mem.span()` in impl).

2022-11-02 22:57 UTC, michal-z commented on libs/zglfw/src/zglfw.zig
> +    pub fn present(self: Joystick) bool {
Actually this should be a global function called `isJoystickPresent(jid: u4) bool`. It should not be possible to create an instance of `Joystick` if it is not present on the system.

2022-11-02 22:57 UTC, michal-z commented on libs/zglfw/src/zglfw.zig
> +    pub fn init(jid: u4) ?Joystick {
I would prefer a global function `getJoystick(jid: u4) ?Joystick`. `init()` function suggests that `deinit()` should be also present.

2022-11-02 22:57 UTC, michal-z commented on libs/zglfw/src/zglfw.zig
> +            return &empty_buttons;
```suggestion
            @as([*]const ButtonAction, undefined)[0..0]
```

2022-11-02 22:57 UTC, michal-z commented on libs/zglfw/src/zglfw.zig
> +            return &empty_axes;
```suggestion
            return @as([*]const f32, undefined)[0..0];
```

2022-11-02 22:57 UTC, michal-z commented on libs/zglfw/src/zglfw.zig
> +    pub fn gamepad(self: Joystick) ?Gamepad {
Let's call it `asGamepad()`.

2022-11-02 22:57 UTC, michal-z commented on libs/zglfw/src/zglfw.zig
> +    pub fn getName(self: Gamepad) []u8 {
Return type should be `[:0]`.

2022-11-02 22:57 UTC, michal-z commented on libs/zglfw/src/zglfw.zig
> +pub fn updateGamepadMappings(mappings: [*:0]const u8) bool {
```suggestion
pub fn updateGamepadMappings(mappings: [:0]const u8) bool {
```

2022-11-02 22:57 UTC, michal-z commented on libs/zglfw/src/zglfw.zig
> +    pub fn init(jid: u4) ?Gamepad {
`init()` suggests that the object is constructed and that `deinit()` should be called to destruct it. Let's remove this function.

```zig
if (zglfw.getJoystick(1)) |joystick| {
    if (joystick.asGamepad()) |gamepad| {
    }
}
```

2022-11-03 03:02 UTC, Pyrolistical commented
Thanks for the feedback! I've incorporated it all.

2022-11-03 11:34 UTC, michal-z commented
Looks good, thanks!

2022-11-03 11:34 UTC, merged

2022-11-03 16:37 UTC, Pyrolistical commented
Thanks, I would just like to reflect on the steps we took here and I think it may serve as a good template for future contributions.

1. Create strawman api/implementation and sample using it
2. Debate strawman to decide on better api/implementation design
3. Execute on better api/implementation design
4. Last review to nitpick final details such as code conventions and better types

2022-11-03 17:25 UTC, michal-z commented
Sounds good, should we publish those steps somewhere? WHat do you think?

2022-11-03 18:37 UTC, Pyrolistical commented
Let's do this again first