zstbi: Added HDR support to Image.loadFromMemory()
michal-z/zig-gamedev pull request #231
Opened 2023-02-28 20:43 UTC by soenkekrusche

I am fairly new to zig, but used stbi in the past. I am not very deep into the internas of it.
I tried to puzzle together what has to be done with existing code and the stbi.h

I am not sure if I built zstbi successfully as it is a library. I would appreciate if someone could tell me a way to test if my changes do remotely what I think :)

2023-02-28 20:57 UTC, michal-z requested changes

2023-02-28 20:57 UTC, michal-z commented on libs/zstbi/src/zstbi.zig
> +            bytes_per_component = 1;
We use `f16` for each component so `bytes_per_component` should be 2.

2023-02-28 20:57 UTC, michal-z commented
Thanks for the PR! It looks good. I found one issue/typo.

2023-02-28 21:01 UTC, michal-z commented
To test it we would have to create a small test app (or modify existing sample app). This is not strictly necessary as part of this PR.

2023-03-01 06:08 UTC, soenkekrusche commented
I will resolve the issue after work and try to write a test or simple test app, no promises for that tho

2023-03-01 21:21 UTC, merged