dxgi: Add support for ReportLiveObjects
michal-z/zig-gamedev pull request #292
Opened 2023-05-09 14:07 UTC by gmodarelli

Hello, I'm trying to add support for `ReportLiveObjects()`, but I'm getting a segmentation fault upon invocation and I can't figure out why.

I hope opening a PR might move things along :)

<img width="742" alt="image" src="https://github.com/michal-z/zig-gamedev/assets/579525/bcce4d64-4c2f-435d-9094-1bb3a7083ac3">

2023-05-09 17:56 UTC, michal-z commented
I'm not sure but I think that this is old D3D11 API, for D3D12 we should be using https://learn.microsoft.com/en-us/windows/win32/api/d3d12sdklayers/nf-d3d12sdklayers-id3d12debugdevice-reportlivedeviceobjects

2023-05-09 19:26 UTC, gmodarelli commented
Perfect, thanks for the info. I'll update the PR :)

2023-05-09 20:26 UTC, gmodarelli commented
I think I've managed to get it to work. I've simulated a leak by not deleting a fence and now I get this message in the debug output window 

<img width="659" alt="image" src="https://github.com/michal-z/zig-gamedev/assets/579525/d1f3af04-4fc3-4bc6-b5b0-ff6f96754a1b">

2023-05-09 21:55 UTC, michal-z requested changes
Thnaks! I've added few comments.

2023-05-09 21:55 UTC, michal-z commented on libs/zd3d12/src/zd3d12.zig
> +        if (enable_debug_layer) {
```suggestion
        if (gctx.debug_device) |debug_device| {
```

2023-05-09 21:55 UTC, michal-z commented on libs/zd3d12/src/zd3d12.zig
> +    debug_device: *d3d12.IDebugDevice,
Let's make it an optional (`?*d3d12.IDebugDevice`) and set it to `null` when debug layer is disabled. In that way users of `zd3d12` module will know if they can use this field.

2023-05-10 06:05 UTC, gmodarelli commented
Thanks for the review!

2023-05-10 09:52 UTC, michal-z requested changes
Just a super minor change. I think this is simpler because we have only one conditional now.

2023-05-10 09:52 UTC, michal-z commented on libs/zd3d12/src/zd3d12.zig
> +        var debug_device: *d3d12.IDebugDevice = undefined;
```suggestion
        var debug_device: ?*d3d12.IDebugDevice = null;
```

2023-05-10 09:52 UTC, michal-z commented on libs/zd3d12/src/zd3d12.zig
> +            .debug_device = if (enable_debug_layer) debug_device else null,
```suggestion
            .debug_device = debug_device,
```

2023-05-10 10:04 UTC, merged